landmark_pose_estimation_node:
  silo_1_YLine: [-3.0, -1.5]
  silo_1_TJunction: [-2.75, -1.5]

  silo_2_YLine: [-3.0, -0.75]
  silo_2_TJunction: [-2.75, -0.75]

  silo_3_YLine: [-3.0, 0.0]  
  silo_3_TJunction: [-2.75, 0.0]

  silo_4_YLine: [-3.0, 0.75]
  silo_4_TJunction: [-2.75, 0.75]

  silo_5_YLine: [-3.0, 1.50]
  silo_5_RJunction: [-2.75, 1.50]

  cross_junction: [-2.75, 0.0]

  x_horizontal_line: [-2.75, 0.0]
  y_vertical_line: [2.0, 0.0]

